language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.6
 - 7.0
 - 7.1

addons:
  postgresql: 9.4

env:
  global:
  - IGNORE_PATHS=amd/build
  matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  # Allow failures because 3.2 is not longer supported.
  allow_failures:
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  exclude:
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=master
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=master
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install v8.9.4
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
      - moodle-plugin-ci validate

# Default 'test' stage: Unit tests and behat tests against full matrix.
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - test
